"""Composizione dell'area di lavoro: sorgente FC e destinazione locale affiancate."""

import sys

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QCheckBox, QComboBox, QFrame, QHBoxLayout, QHeaderView, QLabel, QProgressBar,
    QSplitter, QStackedWidget, QVBoxLayout, QWidget,
)

from .browser import FCLogTable, LocalBrowser


def build_workspace(window, icon):
    w = window
    root = QWidget()
    root.setObjectName("body")
    w.setCentralWidget(root)
    outer = QVBoxLayout(root)
    outer.setContentsMargins(0, 0, 0, 0)
    outer.setSpacing(0)
    if w.demo:
        outer.addWidget(w.label("Modalità demo: file di esempio. Nessun dispositivo reale viene utilizzato.", "banner"))
    header = QHBoxLayout()
    header.setContentsMargins(22, 17, 22, 17)
    header.setSpacing(11)
    mark = QLabel()
    mark.setPixmap(icon(32))
    header.addWidget(mark)
    header.addWidget(w.label("Betaflight Blackbox Desk", "title"))
    header.addStretch()
    header.addWidget(w.label("Trascina i log dalla FC al computer", "muted"))
    header.addSpacing(12)
    header.addWidget(w.button("Informazioni", w.about, "small"))
    outer.addLayout(header)

    w.splitter = QSplitter(Qt.Orientation.Horizontal)
    w.splitter.setChildrenCollapsible(False)
    w.splitter.setHandleWidth(5)
    fc = QFrame()
    fc.setObjectName("fcPane")
    fc.setMinimumWidth(480)
    left = QVBoxLayout(fc)
    left.setContentsMargins(20, 18, 17, 18)
    left.setSpacing(10)
    left.addWidget(w.label("Flight controller", "paneTitle"))
    connect = QHBoxLayout()
    w.device_combo = QComboBox()
    w.device_combo.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
    w.device_combo.setMinimumContentsLength(12)
    w.device_combo.addItem("Cerca una FC collegata", None)
    w.device_combo.currentIndexChanged.connect(w.update_actions)
    connect.addWidget(w.device_combo, 1)
    w.scan_button = w.button("Cerca", w.scan)
    w.connect_button = w.button("Connetti", w.connect_device)
    connect.addWidget(w.scan_button)
    connect.addWidget(w.connect_button)
    left.addLayout(connect)
    w.connection_title = w.label("Nessuna FC collegata", "connection", True)
    w.connection_detail = w.label("Collega il drone e chiudi la connessione in Betaflight.", "muted", True)
    left.addWidget(w.connection_title)
    left.addWidget(w.connection_detail)
    selection = QHBoxLayout()
    w.total_label = w.label("Nessuna memoria aperta", "muted")
    selection.addWidget(w.total_label, 1)
    w.all_button = w.button("Tutti", lambda: w.select_rows(True), "small")
    w.none_button = w.button("Nessuno", lambda: w.select_rows(False), "small")
    w.refresh_button = w.button("Aggiorna", w.refresh, "small")
    for button in (w.all_button, w.none_button, w.refresh_button):
        selection.addWidget(button)
    left.addLayout(selection)
    w.stack = QStackedWidget()
    w.table = FCLogTable(w)
    w.table.setHorizontalHeaderLabels(["Log", "Registrato", "Dimensione", "Stato"])
    w.table.verticalHeader().hide()
    w.table.verticalHeader().setDefaultSectionSize(36)
    w.table.setAlternatingRowColors(True)
    w.table.setShowGrid(False)
    w.table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
    w.table.horizontalHeader().setDefaultAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
    for column, width in [(1, 146), (2, 90), (3, 96)]:
        w.table.setColumnWidth(column, width)
    w.table.itemSelectionChanged.connect(w.update_actions)
    w.stack.addWidget(w.table)
    empty = QWidget()
    empty_layout = QVBoxLayout(empty)
    empty_layout.addStretch()
    w.empty_title = w.label("Collega la tua FC", "emptyTitle")
    w.empty_detail = w.label("Premi Cerca e Connetti\nper vedere i log nella memoria.", "muted", True)
    for label in (w.empty_title, w.empty_detail):
        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        empty_layout.addWidget(label)
    empty_layout.addStretch()
    w.stack.addWidget(empty)
    w.stack.setCurrentIndex(1)
    left.addWidget(w.stack, 1)
    w.selection_label = w.label("Nessun log selezionato", "muted")
    left.addWidget(w.selection_label)
    copy_actions = QHBoxLayout()
    w.latest_button = w.button("Copia ultimo", w.copy_latest)
    w.copy_button = w.button("Copia selezionati →", w.copy_selected, "primary")
    copy_actions.addWidget(w.latest_button)
    copy_actions.addWidget(w.copy_button, 1)
    left.addLayout(copy_actions)
    device_actions = QHBoxLayout()
    w.delete_button = w.button("Elimina selezionati", w.delete_selected, "danger")
    w.reset_button = w.button("Svuota memoria…", w.reset_memory, "danger")
    w.eject_button = w.button("Espelli FC", w.eject)
    for button in (w.delete_button, w.reset_button, w.eject_button):
        device_actions.addWidget(button)
    left.addLayout(device_actions)
    w.capability = w.label("Compatibile con Betaflight e modalità disco USB.", "capability", True)
    w.capability.setMinimumHeight(38)
    left.addWidget(w.capability)
    w.splitter.addWidget(fc)

    local = QFrame()
    local.setObjectName("localPane")
    local.setMinimumWidth(460)
    right = QVBoxLayout(local)
    right.setContentsMargins(17, 18, 20, 18)
    right.setSpacing(10)
    right.addWidget(w.label("Computer", "paneTitle"))
    w.browser = LocalBrowser(w.destination, w.can_drop_logs, w.drop_logs)
    w.browser.path_changed.connect(w.destination_changed)
    w.browser.message.connect(lambda text: w.status.setText(text))
    w.browser.new_folder_button.clicked.connect(w.create_local_folder)
    w.browser.trash_button.clicked.connect(w.trash_local_selected)
    w.choose_button = w.browser.choose_button
    w.destination_label = w.browser.path_edit
    right.addWidget(w.browser, 1)
    options = QHBoxLayout()
    w.auto_eject = QCheckBox("Espelli FC dopo la copia")
    w.auto_eject.setChecked(True if not w.interactive or w.demo else w.settings.value("auto_eject", True, type=bool))
    w.auto_eject.toggled.connect(w.save_preferences)
    options.addWidget(w.auto_eject)
    options.addStretch()
    w.open_button = w.button("Apri nel Finder" if sys.platform == "darwin" else "Apri cartella", w.open_destination)
    options.addWidget(w.open_button)
    right.addLayout(options)
    note = w.label("Le copie mantengono il nome originale e vengono verificate e sbloccate.", "muted", True)
    note.setMinimumHeight(38)
    right.addWidget(note)
    w.splitter.addWidget(local)
    w.splitter.setSizes([600, 600])
    outer.addWidget(w.splitter, 1)

    footer = QVBoxLayout()
    footer.setContentsMargins(22, 10, 22, 12)
    w.progress = QProgressBar()
    w.progress.setTextVisible(False)
    w.progress.setFixedHeight(6)
    w.progress.hide()
    footer.addWidget(w.progress)
    status = QHBoxLayout()
    w.status = w.label("Scegli la cartella sul computer, poi collega la FC.", "muted", True)
    w.status.setMinimumHeight(30)
    status.addWidget(w.status, 1)
    w.cancel_button = w.button("Annulla", w.cancel, "small")
    w.cancel_button.hide()
    status.addWidget(w.cancel_button)
    footer.addLayout(status)
    outer.addLayout(footer)
