"""Workspace layout: flight controller source and local destination side by side."""

import sys

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QCheckBox, QComboBox, QFrame, QHBoxLayout, QHeaderView, QLabel, QProgressBar,
    QSplitter, QStackedWidget, QVBoxLayout, QWidget,
)

from .browser import FCLogTable, LocalBrowser


def build_workspace(window, icon):
    w = window
    root = QWidget()
    root.setObjectName("body")
    w.setCentralWidget(root)
    outer = QVBoxLayout(root)
    outer.setContentsMargins(0, 0, 0, 0)
    outer.setSpacing(0)
    if w.demo:
        outer.addWidget(w.label("Demo mode: sample files only. No real device is used.", "banner"))
    header = QHBoxLayout()
    header.setContentsMargins(22, 17, 22, 17)
    header.setSpacing(11)
    mark = QLabel()
    mark.setPixmap(icon(32))
    header.addWidget(mark)
    header.addWidget(w.label("Betaflight Blackbox Desk", "title"))
    header.addStretch()
    header.addWidget(w.label("Drag logs from the flight controller to your computer", "muted"))
    header.addSpacing(12)
    header.addWidget(w.button("About", w.about, "small"))
    outer.addLayout(header)

    w.splitter = QSplitter(Qt.Orientation.Horizontal)
    w.splitter.setChildrenCollapsible(False)
    w.splitter.setHandleWidth(5)
    fc = QFrame()
    fc.setObjectName("fcPane")
    fc.setMinimumWidth(480)
    left = QVBoxLayout(fc)
    left.setContentsMargins(20, 18, 17, 18)
    left.setSpacing(10)
    left.addWidget(w.label("Flight controller", "paneTitle"))
    connect = QHBoxLayout()
    w.device_combo = QComboBox()
    w.device_combo.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
    w.device_combo.setMinimumContentsLength(12)
    w.device_combo.addItem("Search for a connected flight controller", None)
    w.device_combo.currentIndexChanged.connect(w.update_actions)
    connect.addWidget(w.device_combo, 1)
    w.scan_button = w.button("Search", w.scan)
    w.connect_button = w.button("Connect", w.connect_device)
    connect.addWidget(w.scan_button)
    connect.addWidget(w.connect_button)
    left.addLayout(connect)
    w.connection_title = w.label("No flight controller connected", "connection", True)
    w.connection_detail = w.label("Connect the drone and close its connection in Betaflight.", "muted", True)
    left.addWidget(w.connection_title)
    left.addWidget(w.connection_detail)
    selection = QHBoxLayout()
    w.total_label = w.label("No storage open", "muted")
    selection.addWidget(w.total_label, 1)
    w.all_button = w.button("All", lambda: w.select_rows(True), "small")
    w.none_button = w.button("None", lambda: w.select_rows(False), "small")
    w.refresh_button = w.button("Refresh", w.refresh, "small")
    for button in (w.all_button, w.none_button, w.refresh_button):
        selection.addWidget(button)
    left.addLayout(selection)
    w.stack = QStackedWidget()
    w.table = FCLogTable(w)
    w.table.setHorizontalHeaderLabels(["Log", "Recorded", "Size", "Status"])
    w.table.verticalHeader().hide()
    w.table.verticalHeader().setDefaultSectionSize(36)
    w.table.setAlternatingRowColors(True)
    w.table.setShowGrid(False)
    w.table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
    w.table.horizontalHeader().setDefaultAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
    for column, width in [(1, 146), (2, 90), (3, 96)]:
        w.table.setColumnWidth(column, width)
    w.table.itemSelectionChanged.connect(w.update_actions)
    w.stack.addWidget(w.table)
    empty = QWidget()
    empty_layout = QVBoxLayout(empty)
    empty_layout.addStretch()
    w.empty_title = w.label("Connect your flight controller", "emptyTitle")
    w.empty_detail = w.label("Press Search and Connect\nto view logs in storage.", "muted", True)
    for label in (w.empty_title, w.empty_detail):
        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        empty_layout.addWidget(label)
    empty_layout.addStretch()
    w.stack.addWidget(empty)
    w.stack.setCurrentIndex(1)
    left.addWidget(w.stack, 1)
    w.selection_label = w.label("No logs selected", "muted")
    left.addWidget(w.selection_label)
    copy_actions = QHBoxLayout()
    w.latest_button = w.button("Copy latest", w.copy_latest)
    w.copy_button = w.button("Copy selected →", w.copy_selected, "primary")
    copy_actions.addWidget(w.latest_button)
    copy_actions.addWidget(w.copy_button, 1)
    left.addLayout(copy_actions)
    device_actions = QHBoxLayout()
    w.delete_button = w.button("Delete selected", w.delete_selected, "danger")
    w.reset_button = w.button("Empty storage…", w.reset_memory, "danger")
    w.eject_button = w.button("Eject flight controller", w.eject)
    for button in (w.delete_button, w.reset_button, w.eject_button):
        device_actions.addWidget(button)
    left.addLayout(device_actions)
    w.capability = w.label("Compatible with Betaflight and USB Mass Storage mode.", "capability", True)
    w.capability.setMinimumHeight(38)
    left.addWidget(w.capability)
    w.splitter.addWidget(fc)

    local = QFrame()
    local.setObjectName("localPane")
    local.setMinimumWidth(460)
    right = QVBoxLayout(local)
    right.setContentsMargins(17, 18, 20, 18)
    right.setSpacing(10)
    right.addWidget(w.label("Computer", "paneTitle"))
    w.browser = LocalBrowser(w.destination, w.can_drop_logs, w.drop_logs)
    w.browser.path_changed.connect(w.destination_changed)
    w.browser.message.connect(lambda text: w.status.setText(text))
    w.browser.new_folder_button.clicked.connect(w.create_local_folder)
    w.browser.trash_button.clicked.connect(w.trash_local_selected)
    w.choose_button = w.browser.choose_button
    w.destination_label = w.browser.path_edit
    right.addWidget(w.browser, 1)
    options = QHBoxLayout()
    w.auto_eject = QCheckBox("Eject flight controller after copying")
    w.auto_eject.setChecked(True if not w.interactive or w.demo else w.settings.value("auto_eject", True, type=bool))
    w.auto_eject.toggled.connect(w.save_preferences)
    options.addWidget(w.auto_eject)
    options.addStretch()
    w.open_button = w.button("Open in Finder" if sys.platform == "darwin" else "Open folder", w.open_destination)
    options.addWidget(w.open_button)
    right.addLayout(options)
    note = w.label("Copies retain their original name and are verified and unlocked.", "muted", True)
    note.setMinimumHeight(38)
    right.addWidget(note)
    w.splitter.addWidget(local)
    w.splitter.setSizes([600, 600])
    outer.addWidget(w.splitter, 1)

    footer = QVBoxLayout()
    footer.setContentsMargins(22, 10, 22, 12)
    w.progress = QProgressBar()
    w.progress.setTextVisible(False)
    w.progress.setFixedHeight(6)
    w.progress.hide()
    footer.addWidget(w.progress)
    status = QHBoxLayout()
    w.status = w.label("Choose a folder on your computer, then connect the flight controller.", "muted", True)
    w.status.setMinimumHeight(30)
    status.addWidget(w.status, 1)
    w.cancel_button = w.button("Cancel", w.cancel, "small")
    w.cancel_button.hide()
    status.addWidget(w.cancel_button)
    footer.addLayout(status)
    outer.addLayout(footer)
